name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # 每天国际标准时间0点（北京时间早8点）自动同步
  workflow_dispatch: # 允许手动点按钮触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: sub-store-org/Sub-Store
          upstream_sync_branch: master
          target_sync_branch: master
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          test_mode: false
